#import "@preview/ilm:1.4.1": *
#import "@preview/physica:0.9.5": *
#import "@preview/thmbox:0.2.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node, shapes
#import "@preview/xarrow:0.3.1": xarrow, xarrowLeftRight

#set page(margin: (
  top: 0.5in,
  bottom: 0.5in,
  x: 0.5in,
))

#show: thmbox-init(counter-level: 2)
#set text(lang: "en")
#set figure(numbering: none)

#let definition-counter = counter("definition")
#show: sectioned-counter(definition-counter, level: 2)
#let definition = definition.with(counter: definition-counter)

#show: ilm.with(
  title: [Computer Networks],
  author: "",
  abstract: [],
)

= Introduction

#definition[Computer Network][
  It is a collection of interconnected computing devices that can exchange data and share resources, using agreed-upon communication protocols over a communication medium. Mathematically, it is just a graph,
  $ G = (V, E) $
  where, $V$ is the set of nodes and $E$ represents the communication links.
]

#definition[Node][
  These are entities in the network. It is any device capable of sending or receiving the data generated by other nodes on the network. E.g.
  - *End Systems (Hosts):* PCs, smartphones, servers
  - *Intermediary Devices:* switches, routers, gateways
]

#definition[Links][
  These are communication channels between nodes:
  - *Guided Media:* copper cables, optical fiber
  - *Unguided Media:* radio, microwaves, satellite
]

A computer network is considered effective if it satisfies three broad criteria:
- *Performance* measures how well the network delivers under expected and peak conditions. It can be measured in terms of transit time#footnote[time required for a message to travel from one device to another] and response time#footnote[time between an enquiry and response].
- *Reliability* is the probability that the network will deliver correct data to the correct destination within the required time without failure.
- *Security* ensures confidentiality, integrity and availability#footnote[CIA lol] of data and services.

Some common components of a computer network are:
- *Message* is the information to be communicated between entities. It can be text, numbers, audio, etc. but formally it is just an element of ${0, 1}^*$. It is the _payload_ of the communication.
- *Sender* is the entity that originates the message. It converts the message into a suitable transmittable signal and initialises the delivery.
- *Receiver* is the entity that accepts and interprets the message. It takes the incoming signals, converts them back into the original data and presents them to the application/user.
- *Transmission Medium* is the physical path or channel through which signals travel from sender to receiver. It carries the encoded signal from source to destination.
- *Protocol* is a set of rules and conventions for communication between entities. Formally, it is a finite-state machine $("Set of States", "Inputs", "Outputs", "Transition Function")$. It defines the message format (syntax), specifies the meaning of fields (semantics) and describes timing, ordering and error handling.
- *Encoder* converts message data into a signal suitable for the medium (modulation, coding).
- *Decoder* converts received signals back into the original data.
A communication system can be defined as a set of processes (like encoding, transmission, routing, decoding) that use the sender message, receiver, medium and protocol.

There are three types of message flow directions:
- *Simplex Communication* is when data flows in one direction only, the sender always sends and the receiver always receives.
$ S xarrow("m") R $
It is easy to implement and the full bandwidth is available for sending only, however, it has no feedback and thus errors cannot be corrected in real time.
- *Half-Duplex* is when data flows in both directions, but only one direction at a time.
$ S xarrow("m"_1) R space "then" space R xarrow("m"_2) S $
It uses a control protocol to decide whose turn it is to send. It is more efficient than simplex for two-way exchange and costs less than full-duplex, however, time is lost in switching directions and potential collisions if both try to send at the same time.
- *Full-Duplex* is when data flows in both directions simultaneously.
$ S xarrowLeftRight("   m   ") R $
It requires separate channels for each direction or clever signal separation (echo cancellation) and no turn-taking is required. It has maximum efficiency for real-time interaction and does not require waiting to respond, however, it is more complex and expensive and higher potential for interference if separation is not perfect.

#definition[Topology][
  It is the arrangement of nodes and links in a network, describing how nodes are physically connected or logically interconnected and how data flows through them. The topology is the specific structure of $G$, i.e. which nodes are connected to which and in what pattern.
]
*Physical Topology* describes the actual physical layout of devices and cables while *Logical Topology* describes the data flow paths, regardless of the physical layout.

We analyse a topology on the basis of its _degree_, _diameter_, _redundancy_, _scalability_ and _fault_tolerance_. The topology of a network effects its performance, reliability, cost and protocol design.

#pagebreak()

#figure(
  table(
    columns: 7,
    inset: 8pt,
    align: horizon,
    table.header(
      [*Topology*],
      [*Structure*],
      [*Advantages*],
      [*Disadvantages*],
      [*Example*],
      [*Number of Links*],
      [*Number of Ports*],
    ),

    // Bus
    [*Bus*],
    [All nodes share a single backbone cable],
    [Easy to implement, low cost],
    [Entire network fails if main cable breaks, collisions],
    [Early Ethernet],
    [$n - 1$],
    // Links
    [$n$],
    // Ports

    // Star
    [*Star*],
    [All nodes connect to a central hub/switch],
    [Easy to add/remove nodes, fault isolation],
    [Central device failure brings network down],
    [Modern Ethernet],
    [$n$],
    [$n$],

    // Ring
    [*Ring*],
    [Each node connects to two others forming a loop],
    [Predictable performance],
    [One failure can disrupt unless dual ring],
    [FDDI, some Metro networks],
    [$n$],
    [$2n$],

    // Mesh
    [*Mesh*],
    [Every node connects to every other],
    [High redundancy, fault tolerance],
    [Expensive, complex cabling],
    [WAN backbones],
    [$(n(n-1))/2$],
    [$n(n-1)$],

    // Tree
    [*Tree\
      (Hierarchical)*],
    [Star networks arranged in hierarchy],
    [Scalable],
    [Failure of root affects large part],
    [Corporate LANs],
    [$n - 1$],
    [Varies],

    // Hybrid
    [*Hybrid*],
    [Combination of above],
    [Flexible design],
    [Complexity in planning],
    [Large enterprise networks],
    [Depends],
    [Depends],
  ),
)

#figure(
  image("imgs/Types-Of-Topologies.png", height: 25%),
  caption: [Types of Topologies],
)

The different types of networks based on geographical location are:
#columns(2)[
  - *Personal Area Network (PAN)* Few meters
  - *Local Area Network (LAN)* Few kilometers
  - *Metropolitan Area Network (MAN)* 5-50 km
  - *Wide Area Network (WAN)* $10^3-10^4$ km
  #colbreak()
  - *Wireless LAN (WLAN)*
  - *Campus Area Network (CAN)*
  - *Storage Area Network (SAN)*
]

#definition[Protocol][
  A protocol is a set of rules that govern data communications. A protocol defines what is communicated, how it is communicated and when it is communicated.
]
The key elements of a protocol are:
- *Syntax* refers to the structure of the data
- *Semantics* refers to the meanings of each section of bits
- *Timing* refers to when data should be sent and how fast they can be sent

#definition[Standards][
  Standards provide guidelines to manufacturers, vendors, government agencies, and other service providers to ensure the kind of interconnectivity necessary in today's marketplace and in international communications.
]

== Open Systems Interconnection Model

It is a conceptual framework#footnote[It is not a protocol, just a model for understanding and designing a network architecture that is flexible, robust, and interoperable] developed by the International Organization for Standardization (ISO) in 1984 to standardize how different networking systems communicate with each other. It serves the following purposes:
- Standardizes communication functions across hardware/software vendors
- Ensures interoperability between devices (e.g., computers, routers, switches)
- Breaks down complex networking into manageable parts
- Provides clear separation of responsibilities
- Serves as a reference model#footnote[This shit model (actually better than TCP) is not really even used]

#figure(
  image("imgs/OSI-Layers.png", height: 40%),
  caption: [Layers and Communication],
)

The layers which do not specifically have a unit but need introduction are:
- *Session Layer:* It acts as the network dialog controller – manages, maintains, and synchronizes communication between two systems. Performs *dialog control*, i.e. allows communication in half-duplex or full-duplex and *synchronization*, i.e. adds checkpoints to long data streams (e.g., after every 100 pages of a file transfer). Thus, if a crash happens, only the data after the last checkpoint needs to be resent, not the entire stream.
- *Presentation Layer:* It handles the syntax and semantics of data – makes sure information is understandable by both systems. Performs *translation*, i.e. converts data from sender’s format → common format → receiver’s format (ensures interoperability between different encoding systems), *encryption/decryption*, i.e. provides privacy and security by transforming sensitive data before transmission and *compression/decompression*, i.e. reduces data size to optimize transmission, especially for multimedia (text, audio, video).

= Physical Layer

It is responsible for the movement of raw bits (0s and 1s) over a physical medium from one node to another. The main functions are:
- *Physical Characteristics of Interfaces & Medium:* Defines hardware specifications (cables, connectors, voltages, frequencies, etc.) and specifies the type of transmission medium (copper, fiber, wireless)
- *Representation of Bits:* Converts bits into signals (electrical, optical, or radio) and defines encoding schemes (e.g., NRZ, Manchester encoding)
- *Data Rate:* Defines bit rate (number of bits transmitted per second) and determines bit duration (time per bit)
- *Synchronization of Bits:* Ensures sender and receiver clocks are synchronized at the bit level
- *Line Configuration:* Defines connection setup (either _point-to-point_#footnote[Dedicated link between two devices] or _multipoint_#footnote[Multiple devices share the same link])
- *Physical Topology:* Defines network layout (bus, star, mesh)
- *Transmission Mode:* Defines direction of communication (simplex, half-duplex, full-duplex)

The data usable to a person/application must first be transformed into electromagnetic signals to be transmitted over the physical medium.

== Analog Signals
#definition[Analog Data#footnote[Not very important in our syllabus]][
  It refers to information that is continuous and can take on any value within a given range. It is defined as $x(t) in bb(R)$ for continuous $t$.
]
Mathematically, a periodic analog signal is represented by a _sine_ wave,
$
  s(t) = "Amplitude" dot sin(2 pi "Frequency" t + "Phase") = A dot sin(2 pi f + phi)
$
$2 pi f t$ is called the _angular frequency_.

Some important properties of a sine wave are:
- *Wavelength:* Physical distance a wave occupies in one cycle. $lambda = display(v / f)$
- *Period and Frequency:* Period is the time taken to complete one cycle.  $T = display(1 / f)$
- *Phase:* How far along a cycle a wave is at $t = 0$
- *Time Domain:* $A(t) "vs" t$
- *Frequency Domain:* $A(f) "vs" f$. This is found using the Fourier Transform#footnote[ECE PTSD].
- *Composite Signals:* A signal with multiple sine wave components. $sum s_i (t)$
- *Bandwidth:* Range of frequencies it contains. $B = f_"max" - f_"min"$

== Digital Signals

#definition[Digital Data][
  It refers to information that is discrete and can take on only specific values within a given range. It is defined as $x[n] in bb(Z)$ for discrete $n$.
]

Since most digital signals#footnote[A digital signal is essentially a composite analog signal] are non-periodic, thus, period and frequency are not appropriate terms to describe it, we use *bit rate*.
#definition[Bit Rate][
  It is the number of bits transmitted per second (bps). $R_b = 1 / T_b$ where $N$ is the number of bits and $T$ is the time in seconds.
]
Moreover, $T_b = "propogation speed" times "bit duration"$ is the *bit interval/length* which is the time duration of a single bit.

=== Transmission of Digital Signals

There are two main methods to transmit digital signals, baseband transmission and broadband tranmission#footnote[This requires modulation].

==== Baseband Transmission

It means sending a digital signal directly over a channel as is, without converting it to multiple frequency bands. Here, the entire bandwidth of the channel is used to transmit a single digital signal. The signal occupies frequencies from $0 "Hz"$#footnote[This means that a DC component is present] to a maximum frequency determined by the signal. It is used in point-to-point links and has a shorter range due to attenuation and noise.

==== Broadband Transmission (with Modulation)

It means modulating digital signals onto carrier waves and transmitting them as analog signals over multiple frequency bands. Here, the available bandwidth of the channel is divided into multiple frequency bands, each capable of carrying a separate signal. The signal does not start  It is used in cable TV and long-distance communication and has a longer range due to better noise immunity.

== Data Rate Limits

#definition[Data Rate][
  It is the maximum number of bits that can be transmitted over a communication channel in a given time period, usually measured in bits per second (bps). It is dependent on the physical properties of the channel like bandwidth, signal-quality and encoding/modulation techniques.
]

= Data-Link Layer

It transforms the raw, unreliable _Physical Layer_ into a reliable link for the _Network Layer_ by ensuring error-free hop-to-hop delivery of frames. The main functions are:
- *Framing:* Converts bit streams from the Network Layer into frames (manageable data units)
- *Physical Addressing:* Adds source and destination addresses in the frame header
- *Flow Control:* Prevents sender from overwhelming receiver by controlling transmission rate
- *Error Control:* Detects and retransmits damaged/lost frames, identifies duplicate frames and uses trailers for error detection (e.g., CRC)
- *Access Control:* Determines which device gets to use the shared link when multiple devices are connected
It ensures node-to-node delivery (not end-to-end). This is called *hop-to-hop delivery*. E.g. To send data from $A -> F$, via the links $A -> B -> E -> F$, each hop has a new frame with its own header/trailer.

= Network Layer

It ensures source-to-destination delivery of packets, possibly across multiple networks (not just one link). The _Data Link Layer_ only ensures hop-to-hop delivery between two directly connected devices but this ensures end-to-end delivery across routers/networks. The main functions are:
- *Logical Addressing:* Provides logical addresses (IP addresses) to uniquely identify sender and receiver across networks (since _Data Link Layer_ (MAC) addresses work locally only)
- *Routing:* Determines the best path for packet delivery across networks and uses routers (or L3 switches) and routing tables to forward packets toward their final destination

= Transport Layer

It ensures process-to-process delivery of the entire message (not just host-to-host). The main functions are:
- *Service-Point Addressing (Port Addressing):* Delivers data to the correct process (application) on that host using port numbers (while _Network Layer_ delivers data to correct host)
- *Segmentation & Reassembly:* Breaks message into segments with sequence numbers and reassembles segments at the destination in the correct order. Detects and replaces missing segments
- *Connection Control:* Connectionless (UDP) or Connection-Oriented (TCP)
- *Flow Control:* Prevents sender from overwhelming receiver and does this end-to-end (between processes not just one link)
- *Error Control:* Ensures entire message arrives without loss, duplication, or corruption, this is achieved using acknowledgments and retransmissions.

= Application Layer

It provides network services directly to the user (human or software). It acts as the interface between the user and the network. The main functions are:
- *Network Virtual Terminal:* Allows remote login by simulating a terminal on the remote host
- *File Transfer, Access, and Management (FTAM):* Enables remote file operations (read, write, retrieve, manage)
- *Mail Services:* Supports e-mail forwarding, storage, and access
- *Directory Services:* Provides global, distributed database information about users, resources, and services
