#import "@preview/ilm:1.4.1": *
#import "@preview/physica:0.9.5": *
#import "@preview/thmbox:0.2.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, node, edge, shapes
#import "@preview/xarrow:0.3.1": xarrow, xarrowLeftRight

#set page(margin: (
  top: 0.5in,
  bottom: 0.5in,
  x: 0.5in
))

#show: thmbox-init(counter-level: 2)
#set text(lang: "en")
#set figure(numbering: none)

#let definition-counter = counter("definition")
#show: sectioned-counter(definition-counter, level: 2)
#let definition = definition.with(counter: definition-counter)

#show: ilm.with(
  title: [Computer Networks],
  author: "",
  abstract: [],
)

= Introduction

#definition[Computer Network][
  It is a collection of interconnected computing devices that can exchange data and share resources, using agreed-upon communication protocols over a communication medium. Mathematically, it is just a graph,
  $ G = (V, E) $
  where, $V$ is the set of nodes and $E$ represents the communication links.
]

#definition[Node][
  These are entities in the network. It is any device capable of sending or receiving the data generated by other nodes on the network. E.g.
  - *End Systems (Hosts):* PCs, smartphones, servers
  - *Intermediary Devices:* switches, routers, gateways
]

#definition[Links][
  These are communication channels between nodes:
  - *Guided Media:* copper cables, optical fiber
  - *Unguided Media:* radio, microwaves, satellite
]

A computer network is considered effective if it satisfies three broad criteria:
- *Performance* measures how well the network delivers under expected and peak conditions. It can be measured in terms of transit time#footnote[time required for a message to travel from one device to another] and response time#footnote[time between an enquiry and response].
- *Reliability* is the probability that the network will deliver correct data to the correct destination within the required time without failure.
- *Security* ensures confidentiality, integrity and availability#footnote[CIA lol] of data and services.

Some common components of a computer network are:
- *Message* is the information to be communicated between entities. It can be text, numbers, audio, etc. but formally it is just an element of ${0, 1}^*$. It is the _payload_ of the communication.
- *Sender* is the entity that originates the message. It converts the message into a suitable transmittable signal and initialises the delivery.
- *Receiver* is the entity that accepts and interprets the message. It takes the incoming signals, converts them back into the original data and presents them to the application/user.
- *Transmission Medium* is the physical path or channel through which signals travel from sender to receiver. It carries the encoded signal from source to destination.
- *Protocol* is a set of rules and conventions for communication between entities. Formally, it is a finite-state machine $("Set of States", "Inputs", "Outputs", "Transition Function")$. It defines the message format (syntax), specifies the meaning of fields (semantics) and describes timing, ordering and error handling.
- *Encoder* converts message data into a signal suitable for the medium (modulation, coding).
- *Decoder* converts received signals back into the original data.
A communication system can be defined as a set of processes (like encoding, transmission, routing, decoding) that use the sender message, receiver, medium and protocol.

There are three types of message flow directions:
- *Simplex Communication* is when data flows in one direction only, the sender always sends and the receiver always receives.
$ S xarrow("m") R $
It is easy to implement and the full bandwidth is available for sending only, however, it has no feedback and thus errors cannot be corrected in real time.
- *Half-Duplex* is when data flows in both directions, but only one direction at a time.
$ S xarrow("m"_1) R space "then" space R xarrow("m"_2) S $
It uses a control protocol to decide whose turn it is to send. It is more efficient than simplex for two-way exchange and costs less than full-duplex, however, time is lost in switching directions and potential collisions if both try to send at the same time.
- *Full-Duplex* is when data flows in both directions simultaneously.
$ S xarrowLeftRight("   m   ") R $
It requires separate channels for each direction or clever signal separation (echo cancellation) and no turn-taking is required. It has maximum efficiency for real-time interaction and does not require waiting to respond, however, it is more complex and expensive and higher potential for interference if separation is not perfect.

#definition[Topology][
  It is the arrangement of nodes and links in a network, describing how nodes are physically connected or logically interconnected and how data flows through them. The topology is the specific structure of $G$, i.e. which nodes are connected to which and in what pattern.
]
*Physical Topology* describes the actual physical layout of devices and cables while *Logical Topology* describes the data flow paths, regardless of the physical layout.

We analyse a topology on the basis of its _degree_, _diameter_, _redundancy_, _scalability_ and _fault_tolerance_. The topology of a network effects its performance, reliability, cost and protocol design.

#pagebreak()

#figure(
  table(
    columns: 7,
    inset: 8pt,
    align: horizon,
    table.header(
      [*Topology*], [*Structure*], [*Advantages*], [*Disadvantages*], [*Example*], [*Number of Links*], [*Number of Ports*],
    ),

    // Bus
    [*Bus*],
    [All nodes share a single backbone cable],
    [Easy to implement, low cost],
    [Entire network fails if main cable breaks, collisions],
    [Early Ethernet],
    [$n - 1$],                 // Links
    [$n$],                     // Ports

    // Star
    [*Star*],
    [All nodes connect to a central hub/switch],
    [Easy to add/remove nodes, fault isolation],
    [Central device failure brings network down],
    [Modern Ethernet],
    [$n$],
    [$n$],

    // Ring
    [*Ring*],
    [Each node connects to two others forming a loop],
    [Predictable performance],
    [One failure can disrupt unless dual ring],
    [FDDI, some Metro networks],
    [$n$],
    [$2n$],

    // Mesh
    [*Mesh*],
    [Every node connects to every other],
    [High redundancy, fault tolerance],
    [Expensive, complex cabling],
    [WAN backbones],
    [$(n(n-1))/2$],
    [$n(n-1)$],

    // Tree
    [*Tree\
    (Hierarchical)*],
    [Star networks arranged in hierarchy],
    [Scalable],
    [Failure of root affects large part],
    [Corporate LANs],
    [$n - 1$],
    [Varies],

    // Hybrid
    [*Hybrid*],
    [Combination of above],
    [Flexible design],
    [Complexity in planning],
    [Large enterprise networks],
    [Depends],
    [Depends],
  ),
)

#figure(
  image("imgs/Types-Of-Topologies.png", height: 25%),
  caption: [Types of Topologies]
)
